name: med_copilot_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  ai_barcode_scanner: ^6.0.1
  intl: ^0.18.0
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  provider: ^6.1.2

flutter:
  uses-material-design: true
